//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class EMPLEADOS
    {
        public EMPLEADOS()
        {
            this.USUARIOS = new HashSet<USUARIOS>();
        }
        [Key]
        [Display(Name = "ID Empleado")]
        public int ID_EMPLEADO { get; set; }
        [Required(ErrorMessage = "Ingrese DNI")]
        [Display(Name = "DNI")]
        public string DNI { get; set; }
        [Required(ErrorMessage = "Ingrese nombre")]
        [Display(Name = "Nombres")]
        public string NOMBRES { get; set; }
        [Required(ErrorMessage = "Ingrese Apellidos")]
        [Display(Name = "Apellidos")]
        public string APELLIDOS { get; set; }
        [Required(ErrorMessage = "Ingrese sexo")]
        [Display(Name = "Sexo")]
        public string SEXO { get; set; }
        [Required(ErrorMessage = "Ingrese hora ingreso")]
        [Display(Name = "Hora Ingreso")]
        public System.TimeSpan HORA_INGRESO { get; set; }
        [Required(ErrorMessage = "Ingrese hora Salida")]
        [Display(Name = "Hora Salida")]
        public System.TimeSpan HORA_SALIDA { get; set; }
        [Required(ErrorMessage = "Ingrese Area")]
        [Display(Name = "Area")]
        public Nullable<int> ID_AREA { get; set; }
        [Required(ErrorMessage = "Ingrese cargo")]
        [Display(Name = "cargo")]
        public Nullable<int> ID_CARGO { get; set; }
        [Required(ErrorMessage = "Ingrese Distrito")]
        [Display(Name = "Distrito")]
        public Nullable<int> ID_DISTRITO { get; set; }
        [Required(ErrorMessage = "Ingrese Direccion")]
        [Display(Name = "Direccion")]
        public string DIRECCION { get; set; }
        [Required(ErrorMessage = "Ingrese Telefono")]
        [Display(Name = "Telefono")]
        public string TELEFONO { get; set; }
        [Required(ErrorMessage = "Ingrese Celular")]
        [Display(Name = "Celular")]
        public string CELULAR { get; set; }
    
        public virtual AREAS AREAS { get; set; }
        public virtual CARGOS CARGOS { get; set; }
        public virtual DISTRITOS DISTRITOS { get; set; }
        public virtual ICollection<USUARIOS> USUARIOS { get; set; }
    }
}
